---
- name: Install and start nginx
  hosts: all
  become: yes

  tasks:
    - name: Installing nginx
      apt:
        name: nginx
        state: present
        update_cache: yes

    - name: Run nginx service
      service:
        name: nginx
        state: started
        enabled: yes
